[package]
name = "ecstasy"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["registry", "registry-ffi", "registry-header", "reflexion"]

[workspace.dependencies]
reflexion = { path = "reflexion" }
registry = { path = "registry" }
registry-ffi = { path = "registry-ffi" }
registry-header = { path = "registry-header" }

[dev-dependencies]
registry.workspace = true
registry-ffi.workspace = true
registry-header.workspace = true

[dependencies]
reflexion = { path = "reflexion"}
