[package]
name = "Archipel"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["ecstasy-core",  "ecstasy-ffi", "ecstasy", "reflexion"]

[workspace.dependencies]
reflexion = { path = "reflexion" }
ecstasy-core = { path = "ecstasy-core" }
ecstasy-ffi = { path = "ecstasy-ffi" }
ecstasy = { path = "ecstasy" }

[dev-dependencies]
ecstasy-core.workspace = true
ecstasy-ffi.workspace = true
ecstasy.workspace = true

[dependencies]
reflexion = { path = "reflexion"}
